### ISSUE TITLE
giveaway之前被认定作弊一次之后就无法完成其他任务

### ISSUE THREAD

**Issue by bimyoukyori** [HCLonely/auto-task-old#13]
**关于哪一个网站**

**使用的浏览器和脚本管理器**

**错误信息**

**附加截图**

![image](https://user-images.githubusercontent.com/62165062/76674425-77824480-65ea-11ea-8782-ec586b71aa3e.png)
![image](https://user-images.githubusercontent.com/62165062/76674429-7d782580-65ea-11ea-9953-e42b880758b4.png)

**Comment by HCLonely** [comment]
清一下缓存，然后刷新一下
![image](https://user-images.githubusercontent.com/26346802/76674696-2fb0ec80-65ed-11ea-8ccb-2fb847ab0c35.png)
