### ISSUE TITLE
Nothing workes....

### ISSUE THREAD

**Issue by abolyderechte** [HCLonely/auto-task-old#14]
**关于哪一个网站**

**使用的浏览器和脚本管理器**

**错误信息**

**附加截图**

Nothing workes....

**Comment by HCLonely** [comment]
Which website?

**Comment by abolyderechte** [comment]
Gleam.io

Am 19.03.2020 um 03:39 schrieb HCLonely <notifications@github.com>:

﻿

Which website?

**Comment by HCLonely** [comment]
Please update the script to the latest version and try again.

**Comment by abolyderechte** [comment]
I already did that... :/ it’s says that he did all tasks - but it doesn‘t even solve one

Am 19.03.2020 um 09:13 schrieb HCLonely <notifications@github.com>:

﻿

Please update the script to the latest version and try again.

**Comment by HCLonely** [comment]
Please provide the URL

**Comment by abolyderechte** [comment]
gleam.io

**Comment by HCLonely** [comment]
This script only works on giveaway pages.

**Comment by abolyderechte** [comment]
Yeah sure. Gleam.io is a giveaway page. You even have this site on the settings.

**Comment by HCLonely** [comment]
It only works on URLs like `https://gleam.io/dCzpH/heaven-island-life-giveaway`, not `gleam.io`

**Comment by abolyderechte** [comment]
Yeah sry I meant that. 

You can pick any of them from this database: https://gleamdb.info/
And when you open it, press "FuckTask" it doesn't work

**Comment by HCLonely** [comment]
The ones you said are lotteries, but this script only works for giveaways.

- Not support:
![image](https://user-images.githubusercontent.com/26346802/77051191-e229ea80-6a05-11ea-9046-09a51b537092.png)

- Support:
![image](https://user-images.githubusercontent.com/26346802/77051257-fcfc5f00-6a05-11ea-97dd-79a6ff57f148.png)

**Comment by abolyderechte** [comment]
Please send a working example link for one of these "giveaways"

**Comment by HCLonely** [comment]
Like this: [https://gleam.io/Wsc0y/nira-steam-beta-key-giveaway](https://gleam.io/Wsc0y/nira-steam-beta-key-giveaway)

**Comment by abolyderechte** [comment]
Is there a List or a Database for giveaway like this one?

**Comment by HCLonely** [comment]
No

**Comment by abolyderechte** [comment]
But like 99,9% of everything on gleam are lotteries and no "giveaways"

**Comment by HCLonely** [comment]
Yes. Because there are too many types of lottery tasks, and most tasks cannot be completed directly using scripts, there is no support for lottery.
