### ISSUE TITLE
脚本执行出错，详细信息请查看控制台(红色背景部分)！我是设置的English

### ISSUE THREAD

**Issue by CMZ-GuaYan** [HCLonely/auto-task-old#15]
- [] 我已经按照[安装步骤](https://github.com/HCLonely/auto-task#安装)正确安装了此脚本 | I have installed this script correctly following the [installation](https://github.com/HCLonely/auto-task/blob/master/README_EN.md#Installation).
- [] 我已经将脚本更新到了[最新版](https://userjs.hclonely.com/auto-task.user.js) | I have updated this script to the [latest version](https://userjs.hclonely.com/auto-task.user.js).
- [] 我已经查看了[常见问题解决办法](https://github.com/HCLonely/auto-task#常见问题解决办法)但没有解决 | I have seen [Solutions to common problems](https://github.com/HCLonely/auto-task/blob/master/README_EN.md#solutions-to-common-problems) but not solved.
- [] 我已经查看了[issues](https://github.com/HCLonely/auto-task/issues?q=)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task/issues?q=) but not solved.

**关于哪一个网站，最好提供具体网址（必需）**

**使用的浏览器和脚本管理器**

**错误信息**

**附加截图**

**Comment by CMZ-GuaYan** [comment]
任务执行日志
需要将页面语言设置为"English"(将页面右下角的自动翻译关闭)！如果已设置为"English"，请忽视本条信息
需要将页面语言设置为"English"(将页面右下角的自动翻译关闭)！如果已设置为"English"，请忽视本条信息

**Comment by HCLonely** [comment]
发一下控制台的错误日志

**Comment by CMZ-GuaYan** [comment]
我不知道控制台的错误日志在哪？不是任务执行日志吗？我只会用，不用编程 QAQ...

**Comment by HCLonely** [comment]
按`F12`打开

**Comment by CMZ-GuaYan** [comment]
然后呢？怎么操作？复制console里的内容？

**Comment by HCLonely** [comment]
应该有一部分背景是红色的，只要那一部分

**Comment by CMZ-GuaYan** [comment]
Info:v-on handlerError:TypeError: Cannot set property 'message' of undefined    at Object.fuck (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=2232ff03-3d58-4baa-b687-d40ce4dc85e5:2269:32)    at click (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=2232ff03-3d58-4baa-b687-d40ce4dc85e5:4809:38)    at He (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=2232ff03-3d58-4baa-b687-d40ce4dc85e5:11:11384)    at a.n (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=2232ff03-3d58-4baa-b687-d40ce4dc85e5:11:13168)    at He (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=2232ff03-3d58-4baa-b687-d40ce4dc85e5:11:11384)    at a.e.$emit (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=2232ff03-3d58-4baa-b687-d40ce4dc85e5:11:34373)    at a.handleClick (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=2232ff03-3d58-4baa-b687-d40ce4dc85e5:16:124930)    at He (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=2232ff03-3d58-4baa-b687-d40ce4dc85e5:11:11384)    at HTMLButtonElement.n (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=2232ff03-3d58-4baa-b687-d40ce4dc85e5:11:13168)    at HTMLButtonElement.Yr.o._wrapper (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=2232ff03-3d58-4baa-b687-d40ce4dc85e5:11:48505)

**Comment by HCLonely** [comment]
你是用的最新版吗，我这边没问题

**Comment by CMZ-GuaYan** [comment]
是最新版的，删掉重新装脚本也还是这样

**Comment by HCLonely** [comment]
有js资源加载失败了，参考#8

**Comment by CMZ-GuaYan** [comment]
我是人机验证完后点Init出了问题，我也按照#8打了那个指令。显示：
Uncaught ReferenceError: Centrifuge is not defined
    at <anonymous>:1:1
(anonymous) @ VM3411:1

mc.yandex.ru/clmap/36124145?page-url=https%3A%2F%2Fgivekey.ru%2Fdistribution%2F68&pointer-click=rn%3A906383964%3Ax%3A37448%3Ay%3A27932%3At%3A4143%3Ap%3AWA1A%3AX%3A693%3AY%3A1097&browser-info=ti%3A4%3Arqnl%3A1%3Ast%3A1586881460%3Au%3A1586873503595542138%3App%3A2036073048:1 GET https://mc.yandex.ru/clmap/36124145?page-url=https%3A%2F%2Fgivekey.ru%2Fdistribution%2F68&pointer-click=rn%3A906383964%3Ax%3A37448%3Ay%3A27932%3At%3A4143%3Ap%3AWA1A%3AX%3A693%3AY%3A1097&browser-info=ti%3A4%3Arqnl%3A1%3Ast%3A1586881460%3Au%3A1586873503595542138%3App%3A2036073048 net::ERR_CONNECTION_CLOSED

**Comment by HCLonely** [comment]
那就是有js文件没加载出来，不是脚本的问题，是你网络的问题
你可以等一段时间输一次`Centrifuge`，什么时候不报错就可以正常使用了
