### ISSUE TITLE
一件加入和取消无法实现

### ISSUE THREAD

**Issue by 2957283601** [HCLonely/auto-task-old#16]
![批注 2020-05-01 100616](https://user-images.githubusercontent.com/58629875/80775865-735ab800-8b93-11ea-8c21-c9c3ca73a988.png)
![批注 2020-05-01 100727](https://user-images.githubusercontent.com/58629875/80775919-95543a80-8b93-11ea-9d69-b9c750ab4d2a.png)
如图所示，加入键点击后没有产生作用

**Comment by HCLonely** [comment]
请关闭网页翻译

**Comment by 2957283601** [comment]
谢谢，已解决



---原始邮件---
发件人: "HCLonely"<notifications@github.com&gt;
发送时间: 2020年5月1日(周五) 上午10:50
收件人: "HCLonely/auto-task"<auto-task@noreply.github.com&gt;;
抄送: "2957283601"<2957283601@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [HCLonely/auto-task] 一件加入和取消无法实现 (#16)




 
请关闭网页翻译
