### ISSUE TITLE
gamehag 领KEY按钮无响应

### ISSUE THREAD

**Issue by vbmnvbn** [HCLonely/auto-task-old#18]
**关于哪一个网站**

https://gamehag.com/

**关于哪一项功能**
全部任务完成后 pick up the key按钮 点按无响应问题

**期望的效果**
https://keylol.com/t552134-1-1
能否将此贴2楼脚本加入到 自动完成任务的脚本当中

**Comment by HCLonely** [comment]
在[设置页面](https://userjs.hclonely.com/setting.html)开启`人机验证修复`即可
![image](https://user-images.githubusercontent.com/26346802/84400892-30c9d800-ac35-11ea-90dd-8fc97601ec7f.png)
