### ISSUE TITLE
gamehag 無法自動加退組

### ISSUE THREAD

**Issue by CingYan** [HCLonely/auto-task-old#19]
- [x] 我已经按照[安装步骤](https://github.com/HCLonely/auto-task#安装)正确安装了此脚本 | I have installed this script correctly following the [installation](https://github.com/HCLonely/auto-task/blob/master/README_EN.md#Installation).
- [x] 我已经将脚本更新到了[最新版](https://userjs.hclonely.com/auto-task.user.js) | I have updated this script to the [latest version](https://userjs.hclonely.com/auto-task.user.js).
- [x] 我已经查看了[常见问题解决办法](https://github.com/HCLonely/auto-task#常见问题解决办法)但没有解决 | I have seen [Solutions to common problems](https://github.com/HCLonely/auto-task/blob/master/README_EN.md#solutions-to-common-problems) but not solved.
- [x] 我已经查看了[issues](https://github.com/HCLonely/auto-task/issues?q=)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task/issues?q=) but not solved.

**关于哪一个网站，最好提供具体网址（必需）**

gamehag.com/giveaway/863
準確來說是整個gamehag都有該問題

**使用的浏览器和脚本管理器**

Win10
Chrome(X64) 83.0.4103.97 
Tampermonkey

**错误信息**

(沒有error message)

其實這不算bug Report
gamehag中無法自動加、退steam組
上傳本issus時已逐步重現該問題
1. Auto-task 腳本重新安裝並設定
2. Tampermonkey重新安裝、Auto-Task重新安裝
3. Chrome 刪除cookies、瀏覽紀錄、Tampermonkey重新安裝、Auto-Task重新安裝
皆會出現同樣狀況

但在另外一台Win7環境上一樣的Chrome、Tampermonkey 可自動加退組
並且在其他網頁，如marvelousga可正常加退組、關注取關等
**附加截图**

![flChess Giveaway _ Gamehag - Google Chrome 2020_6_14 下午 11_55_04 (2)](https://user-images.githubusercontent.com/30778297/84598451-77217000-ae9d-11ea-9c69-7783a8cc3b81.png)

**Comment by HCLonely** [comment]
gamehag的加组任务比较少，所以我没做这个功能，之后加上。
