### ISSUE TITLE
opiumpulses not work

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/auto-task-old#20]
- [x] 我已经按照[安装步骤](https://github.com/HCLonely/auto-task#安装)正确安装了此脚本 | I have installed this script correctly following the [installation](https://github.com/HCLonely/auto-task/blob/master/README_EN.md#Installation).
- [x] 我已经将脚本更新到了[最新版](https://userjs.hclonely.com/auto-task.user.js) | I have updated this script to the [latest version](https://userjs.hclonely.com/auto-task.user.js).
- [x] 我已经查看了[常见问题解决办法](https://github.com/HCLonely/auto-task#常见问题解决办法)但没有解决 | I have seen [Solutions to common problems](https://github.com/HCLonely/auto-task/blob/master/README_EN.md#solutions-to-common-problems) but not solved.
- [x] 我已经查看了[issues](https://github.com/HCLonely/auto-task/issues?q=)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task/issues?q=) but not solved.

**关于哪一个网站，最好提供具体网址（必需）**

https://www.opiumpulses.com/giveaways

**使用的浏览器和脚本管理器**

Chrome w/ Tampermonkey

**错误信息**

![image](https://user-images.githubusercontent.com/54498172/84728266-d087bd00-afcb-11ea-9fe1-bd752576588e.png)

**附加截图**

![image](https://user-images.githubusercontent.com/54498172/84728357-02991f00-afcc-11ea-83aa-07fb11c40cad.png)

**Comment by HCLonely** [comment]
It reports no errors and works fine with me.I can't reproduce the problem.
![image](https://user-images.githubusercontent.com/26346802/84729724-f9598380-afc6-11ea-9c57-4d69a0415d11.png)

**Comment by Mishasama** [comment]
Okay, I fixed it after uninstalling and reinstall. Maybe something wrong with the update. Sorry for bothering you.
