### ISSUE TITLE
New website request

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/auto-task-old#21]
**关于哪一个网站**

https://givelab.com

**关于哪一项功能**
Auto task

**期望的效果**
Fuck Task

**Comment by HCLonely** [comment]
At present, it is not possible to implement the functions of "following", "likes", and "retweeting" of social platforms such as twitter, youtube, and facebook through scripts.

**Comment by Mishasama** [comment]
> At present, it is not possible to implement the functions of "following", "likes", and "retweeting" of social platforms such as twitter, youtube, and facebook through scripts.

Maybe just click verify?

**Comment by HCLonely** [comment]
This script will not add support for the site. You can use the following code in the console to click verify:
```javascript
$('.entries-container>.row.step:not(".finished"):not(".hasEmbed")').click();
```

**Comment by Mishasama** [comment]
> This script will not add support for the site. You can use the following code in the console to click verify:
> 
> ```js
> $('.entries-container>.row.step:not(".finished"):not(".hasEmbed")').click();
> ```

Oh, that makes no sense. The click times are much than click it yourself.

**Comment by HCLonely** [comment]
Making it into a script is similar to this.
