### ISSUE TITLE
not working at all and the extensions take sa lot of space on screen

### ISSUE THREAD

**Issue by fisforfaheem** [HCLonely/auto-task-old#22]
pleas ehel pand fix it

**Comment by HCLonely** [comment]
Please provide a URL and a screenshot of the console that are not working

**Comment by fisforfaheem** [comment]
foxed the lots of space...but why this is not doing anything  when i click
fucktask...i mena it should do somehtifg autianmticlaly

**Comment by HCLonely** [comment]
Please provide the URL where you use it and a screenshot of the browser console when you click it so that I can know what went wrong.

**Comment by fisforfaheem** [comment]
sorry cant, but you should improve

**Comment by HCLonely** [comment]
If you can't provide some error message, I can't fix it, because I use it without any problem

**Comment by fisforfaheem** [comment]
no, i deleted it cuz it didnt worked multiple times...especially on android
central and sound guys website. i even deleted the monkey app..so icant
repordouce... you should make it better
