### ISSUE TITLE
Please add https://playr.gg

### ISSUE THREAD

**Issue by Fot3k** [HCLonely/auto-task-old#25]
Adding this website would be amazing, they do a lot of tech giveaways. Even just removing the animations from the drop downs and other elements would speed up entering the giveaways.

https://playr.gg/

Thanks!

**Comment by HCLonely** [comment]
This script has not yet realized the task of automatically completing social platforms such as 'twitter' and 'twitch'.
The animation effect can be removed, but it cannot be accelerated to enter the giveaways, because its animation effect duration depends on your network.
