### ISSUE TITLE
Broken english setting url.

### ISSUE THREAD

**Issue by MIXA798** [HCLonely/auto-task-old#26]
![Screenshot_1](https://user-images.githubusercontent.com/43131783/90017156-c6c0c400-dcb3-11ea-9c16-79e0cf32b427.png)
but it's work if erase "_en" in url

![Screenshot_2](https://user-images.githubusercontent.com/43131783/90017280-f7a0f900-dcb3-11ea-8511-fdf995e78698.png)

**Comment by HCLonely** [comment]
The wrong link has been removed.

**Comment by MIXA798** [comment]
Update link is also broken. 
![Screenshot_4](https://user-images.githubusercontent.com/43131783/90019140-acd4b080-dcb6-11ea-83f2-f34a412094d0.png)
But this link works fine https://github.com/HCLonely/auto-task/raw/master/auto-task-test.user.js
