### ISSUE TITLE
Giveaway.su RU version

### ISSUE THREAD

**Issue by MIXA798** [HCLonely/auto-task-old#27]
As a resident of Russia, I can't use your script on Giveaway.su . When I click on the button to complete the tasks, nothing happens. Can the language of the site affect how the script works?
![Screenshot_3](https://user-images.githubusercontent.com/43131783/90018788-215b1f80-dcb6-11ea-9e81-267afc7e5436.png)

**Comment by HCLonely** [comment]
I judge the task information by the English task name, so if you do not use English, the script cannot get the correct task information.
