### ISSUE TITLE
gamehag网站Verify按钮功能

### ISSUE THREAD

**Issue by vbmnvbn** [HCLonely/auto-task-old#29]
已更新到最新 且 打开 Verify按钮功能 
但最近发现 在点按钮的时候又不好用了

**Comment by HCLonely** [comment]
是怎么不好用了，是报错还是点了没反应？

**Comment by vbmnvbn** [comment]
显示 Incorrect captcha   没有去广告什么的  油猴里也只有本脚本
其他条件不变  关掉本脚本 就好了

**Comment by HCLonely** [comment]
设置页面里找到这个，如果是开启的就关了，如果是关的就开启试试
![image](https://user-images.githubusercontent.com/26346802/95563810-7c0fbe00-0a50-11eb-8dac-4dc82b712bdb.png)

**Comment by vbmnvbn** [comment]
哦 好的 问题解决了谢谢了
