### ISSUE TITLE
add instant gaming?

### ISSUE THREAD

**Issue by Helpme0822** [HCLonely/auto-task-old#34]
Hi i wanted to ask if it's maybe possible to add instant-gaming here's a link to a giveaway:

https://www.instant-gaming.com/en/giveaway/ELOTRIX

**Comment by HCLonely** [comment]
Many of its tasks do not need to be really completed, you can use the following code to complete tasks other than facebook and youtube:
```javascript
$('.ig-contest-social-box>div:not("[id]")>a').map((i, e) => {
  const isCompleted = $(e).hasClass('ig-contest-social-icons-participated')
  if (!isCompleted) {
    const link = $(e).attr('href')
    const channelid = $(e).attr('data-channelid')
    const isFacebook = $(e).hasClass('ig-contest-social-partner-fb') || $(e).hasClass('ig-contest-social-facebook-share')
    if (link !== '#') {
      if (isFacebook) window.open(link, '_blank')
      $(e).removeAttr('href')[0].click()
      $(e).attr('href', link)
    } else if (channelid) {
      window.open('https://www.youtube.com/channel/' + channelid)
    } else if (isFacebook) {
      e.click()
    }
  }
})
```

**Comment by Helpme0822** [comment]
thanks for your answer but I added the code but nothing's showing up when I go on an instant-gaming like I don't get your program showing up to press the button so that it automatically completes the task. I pasted the code you sent at the end of the code. Did I do it wrong or do I have to add something else?

**Comment by HCLonely** [comment]
You shoule paste the code to the console(`Ctrl` + `Shift` + `J`) and then enter.
![image](https://user-images.githubusercontent.com/26346802/101012788-4d204f00-359e-11eb-8ffe-968e6a7700eb.png)
