### ISSUE TITLE
为什么在giveaway.su执行的时候经常会漏掉一两个

### ISSUE THREAD

**Issue by whyjxz14** [HCLonely/auto-task-old#35]
- [] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task/raw/master/auto-task.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task/raw/master/auto-task.user.js).
- [] 我已经查看了[常见问题解决办法](https://github.com/HCLonely/auto-task/wiki/FAQ-zh-CN)但没有解决 | I have seen [FAQ](https://github.com/HCLonely/auto-task/wiki/FAQ) but not solved.
- [] 我已经查看了[issues](https://github.com/HCLonely/auto-task/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task/issues) but not solved.

**关于哪一个网站，最好提供具体网址（必需）**[支持的网站](https://github.com/HCLonely/auto-task/wiki/Website-zh-CN)

比如在https://giveaway.su/giveaway/view/1498上，其中有三个鉴赏家，但是只有
https://store.steampowered.com/curator/27162873/
不会被执行

**使用的浏览器和脚本管理器**

Tampermonkey BETA 4.11.6120
Chrome 86.0.4240.198
**错误信息或截图(重要)**

{
  "result": "Error",
  "statusText": "Error",
  "status": 603,
  "data": {
    "readyState": 4,
    "responseHeaders": "",
    "finalUrl": "https://store.steampowered.com/explore/followgame/",
    "status": 0,
    "statusText": "",
    "responseXML": null,
    "responseText": "",
    "response": null
  },
  "options": {
    "url": "https://store.steampowered.com/explore/followgame/",
    "method": "POST",
    "headers": {
      "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
    },
    "data": "sessionid=1b77bd286da99f11ce5eed39&appid=933070"
  }
}

**Comment by HCLonely** [comment]
603是网络错误，你多试几次

**Comment by whyjxz14** [comment]
绝对不是网络错误啊。每次都是特定的几个失败。你那边无法复现吗



&nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HCLonely/auto-task"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月14日(星期六) 中午12:43
收件人:&nbsp;"HCLonely/auto-task"<auto-task@noreply.github.com&gt;;
抄送:&nbsp;"王弘毅"<799235961@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HCLonely/auto-task] 为什么在giveaway.su执行的时候经常会漏掉一两个 (#35)





 
603是网络错误，你多试几次

**Comment by HCLonely** [comment]
你能提供任务截图和每个任务的连接吗，我的领过了没有任务信息

**Comment by whyjxz14** [comment]
https://giveaway.su/giveaway/view/1198
无法完成的第二个的链接：https://giveaway.su/action/redirect/6981
对应的steam游戏https://store.steampowered.com/app/703600/ASTRAL/
第一个的链接https://giveaway.su/action/redirect/6982
第三个的链接https://giveaway.su/action/redirect/6980
第四个的链接https://giveaway.su/action/redirect/6979
第五个的链接https://giveaway.su/action/redirect/6978
第六个的链接https://giveaway.su/action/redirect/6977





&nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HCLonely/auto-task"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月14日(星期六) 晚上6:16
收件人:&nbsp;"HCLonely/auto-task"<auto-task@noreply.github.com&gt;;
抄送:&nbsp;"王弘毅"<799235961@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HCLonely/auto-task] 为什么在giveaway.su执行的时候经常会漏掉一两个 (#35)





 
你能提供任务截图和每个任务的连接吗，我的领过了没有任务信息

**Comment by HCLonely** [comment]
你使用的是最新版吗，我试了没有问题
