### ISSUE TITLE
大佬你好（已安装辅助脚本）  还是无法验证Discord   错误代码：401  但是我已经登陆了 Discord

### ISSUE THREAD

**Issue by a994849598** [HCLonely/auto-task-old#41]
- [] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task/raw/master/auto-task.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task/raw/master/auto-task.user.js).
- [] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [] 我已经查看了[issues](https://github.com/HCLonely/auto-task/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task/issues) but not solved.

**关于哪一个网站，最好提供具体网址（必需）**[支持的网站](https://auto-task-doc.js.org/guide/#%E6%94%AF%E6%8C%81%E7%9A%84%E7%BD%91%E7%AB%99%E5%8F%8A%E4%BB%BB%E5%8A%A1)

**使用的浏览器和脚本管理器**

**错误信息或截图(重要)**

**Comment by a994849598** [comment]
![image](https://user-images.githubusercontent.com/54111756/113557638-ea64c000-9630-11eb-8932-094d33804643.png)
![image](https://user-images.githubusercontent.com/54111756/113557644-edf84700-9630-11eb-9da3-e33c0d5f9462.png)

**Comment by a994849598** [comment]
![image](https://user-images.githubusercontent.com/54111756/113557671-f9e40900-9630-11eb-8294-1ba9fa130b39.png)

**Comment by HCLonely** [comment]
是这个网址吗？
https://discord.com/channels/@me

**Comment by a994849598** [comment]
是Giveaway 网站  或者是  其他的获取key网站（需要DIscord的  都显示Error：401）

**Comment by a994849598** [comment]
https://giveaway.su/giveaway/view/1834

**Comment by a994849598** [comment]
每次点 更新凭证也无效

**Comment by HCLonely** [comment]
点这个连接更新凭证
https://discord.com/channels/@me

**Comment by a994849598** [comment]
点了 还是 显示  401
