### ISSUE TITLE
gleam.io not work

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/auto-task-old#42]
- [x] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task/raw/master/auto-task.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task/raw/master/auto-task.user.js).
- [x] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [x] 我已经查看了[issues](https://github.com/HCLonely/auto-task/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task/issues) but not solved.

**关于哪一个网站，最好提供具体网址（必需）**[支持的网站](https://auto-task-doc.js.org/guide/#%E6%94%AF%E6%8C%81%E7%9A%84%E7%BD%91%E7%AB%99%E5%8F%8A%E4%BB%BB%E5%8A%A1)

https://gleam.io/GxFo6/cyberpunk-2077-giveaway

**使用的浏览器和脚本管理器**

Chrome Tampermonkey

**错误信息或截图(重要)**

![image](https://user-images.githubusercontent.com/54498172/114946919-10872d00-9e87-11eb-8baf-6c2d4f1e21a4.png)

> `gleam.fuckTypeError: this.get_tasks is not a function    at fuck (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=%25E8%2587%25AA%25E5%258A%25A8%25E4%25BB%25BB%25E5%258A%25A1.user.js&id=5be77094-4a97-4c79-b425-59ffd96f3a04:10030:16)    at <anonymous>:4:80    at i (eval at exec_fn (:2:115), <anonymous>:13:165)    at eval (eval at exec_fn (:2:115), <anonymous>:13:292)    at <anonymous>:13:99    at HTMLDocument.v (<anonymous>:13:118)`

**Comment by HCLonely** [comment]
See #14
