### ISSUE TITLE
Not working after Chrome 90

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/auto-task-old#43]
- [x] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task/raw/master/auto-task.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task/raw/master/auto-task.user.js).
- [x] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [x] 我已经查看了[issues](https://github.com/HCLonely/auto-task/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task/issues) but not solved.

**关于哪一个网站，最好提供具体网址（必需）**[支持的网站](https://auto-task-doc.js.org/guide/#%E6%94%AF%E6%8C%81%E7%9A%84%E7%BD%91%E7%AB%99%E5%8F%8A%E4%BB%BB%E5%8A%A1)

https://auto-task.hclonely.com/setting.html

**使用的浏览器和脚本管理器**

Google Chrome	90.0.4430.93
Tampermonkey	v4.12

**错误信息或截图(重要)**

Noting in the console.
![image](https://user-images.githubusercontent.com/54498172/117854405-6c957380-b2c4-11eb-9b06-4260a6cf9e16.png)
![image](https://user-images.githubusercontent.com/54498172/117854663-abc3c480-b2c4-11eb-9a4c-95b57a50ff07.png)

**Comment by HCLonely** [comment]
我这边是正常的，你看一下你安装的是正式版还是测试版，两个版本的设置页面链接是不一样的

**Comment by Mishasama** [comment]
升级到 90.0.4430.212 就正常了。

**Comment by Mishasama** [comment]
升级到 90.0.4430.212 就正常了。

**Comment by Mishasama** [comment]
![image](https://user-images.githubusercontent.com/54498172/118389609-9f918b80-b665-11eb-8dd9-8e36f951706c.png)
不知道跟这个有没有关系，这个域名我现在貌似经常被重设。
现在其它网站也不能正常工作了。能不能考虑更新一份Github的版本？

**Comment by Mishasama** [comment]
![image](https://user-images.githubusercontent.com/54498172/118389609-9f918b80-b665-11eb-8dd9-8e36f951706c.png)
不知道跟这个有没有关系，这个域名我现在貌似经常被重设。
现在其它网站也不能正常工作了。能不能考虑更新一份Github的版本？

**Comment by HCLonely** [comment]
暂时不会这么弄，以后会把正式版和测试版的设置页面合并，到时候会用github的

**Comment by Mishasama** [comment]
似乎清除了储存的内容之后就正常了，不知道是不是跟储存的内容有关？

**Comment by dourbest** [comment]
dc憑證如何更新呢? 一直過不了
還有我右下角點擊修改設置的按鈕 setting 網頁一直無法進入
![image](https://user-images.githubusercontent.com/20995856/132046078-94d7999c-6f4f-4140-97f4-09516766c521.png)

**Comment by HCLonely** [comment]
> dc憑證如何更新呢? 一直過不了
> 還有我右下角點擊修改設置的按鈕 setting 網頁一直無法進入
> ![image](https://user-images.githubusercontent.com/20995856/132046078-94d7999c-6f4f-4140-97f4-09516766c521.png)

点`更新凭证`啊

**Comment by HCLonely** [comment]
已在 https://github.com/HCLonely/auto-task-v4 中修复
