### ISSUE TITLE
new website: opquests.com

### ISSUE THREAD

**Issue by stickerx** [HCLonely/auto-task-old#46]
**关于哪一个网站**

https://opquests.com/

**关于哪一项功能**

auto-task

**期望的效果**

![download](https://user-images.githubusercontent.com/41187653/135672129-ab1cb6ad-a061-4a06-a92e-9f165f9bba0c.jpg)

**Comment by HCLonely** [comment]
This site will not be supported for the following reason.
![image](https://user-images.githubusercontent.com/26346802/137233874-d2a8492e-8088-4d98-a16e-783b52171e75.png)

**Comment by stickerx** [comment]
can you make her just make the task? 

no, remove

**Comment by stickerx** [comment]
Project completed or still working

**Comment by HCLonely** [comment]
It will be added in Ver 4.x

**Comment by HCLonely** [comment]
已在 https://github.com/HCLonely/auto-task-v4 中实现
