### ISSUE TITLE
It seems it is recognized as cheater,and I'm punished

### ISSUE THREAD

**Issue by fjh1997** [HCLonely/auto-task-old#5]
**关于哪一个网站**

https://giveaway.su/giveaway/view/1569
**使用的浏览器和脚本管理器**

chrome Greasemonkey
**错误信息**

```
WOW! Looks like you are cheater and used some scripts to fake the completion of the tasks.

Do you understand how our service works? Do you realize that Steam keys are provided for a completion of several tasks from our sponsors? Sponsors won't provide Steam keys for giveaways if users won't complete those small tasks. If users complete all tasks - sponsors are happy, we get more sponsors, you get more Steam keys! It's a fair deal, right?

We don't sell Steam keys - we just give away them to our users. That's why we don't have money to give away hundreds of thousands of Steam keys like HumbleBundle or some other big stores. We have to find sponsors. And this is really hard nowadays. But we keep posting at least one giveaway every day.

We are OKAY about scripts helping you to complete tasks faster. But faking the completion of the tasks IS NOT OKAY.

You won't get a key from this giveaway, cheater. Sorry, but if you are going to continue cheating - you will be blocked on our service.
```
**附加截图**

![截屏2020-02-17下午4 20 30](https://user-images.githubusercontent.com/25281816/74635690-7a337a80-51a1-11ea-9cca-2674fa592962.png)

**Comment by HCLonely** [comment]
> **关于哪一个网站**
> 
> https://giveaway.su/giveaway/view/1569
> **使用的浏览器和脚本管理器**
> 
> chrome Greasemonkey
> **错误信息**
> 
> ```
> WOW! Looks like you are cheater and used some scripts to fake the completion of the tasks.
> 
> Do you understand how our service works? Do you realize that Steam keys are provided for a completion of several tasks from our sponsors? Sponsors won't provide Steam keys for giveaways if users won't complete those small tasks. If users complete all tasks - sponsors are happy, we get more sponsors, you get more Steam keys! It's a fair deal, right?
> 
> We don't sell Steam keys - we just give away them to our users. That's why we don't have money to give away hundreds of thousands of Steam keys like HumbleBundle or some other big stores. We have to find sponsors. And this is really hard nowadays. But we keep posting at least one giveaway every day.
> 
> We are OKAY about scripts helping you to complete tasks faster. But faking the completion of the tasks IS NOT OKAY.
> 
> You won't get a key from this giveaway, cheater. Sorry, but if you are going to continue cheating - you will be blocked on our service.
> ```
> 
> **附加截图**
> 
> ![截屏2020-02-17下午4 20 30](https://user-images.githubusercontent.com/25281816/74635690-7a337a80-51a1-11ea-9cca-2674fa592962.png)

After completing the task, please close the script manager and ad blocking plugin.
Then refresh the page and verify again.

**Comment by fjh1997** [comment]
> > **关于哪一个网站**
> > https://giveaway.su/giveaway/view/1569
> > **使用的浏览器和脚本管理器**
> > chrome Greasemonkey
> > **错误信息**
> > ```
> > WOW! Looks like you are cheater and used some scripts to fake the completion of the tasks.
> > 
> > Do you understand how our service works? Do you realize that Steam keys are provided for a completion of several tasks from our sponsors? Sponsors won't provide Steam keys for giveaways if users won't complete those small tasks. If users complete all tasks - sponsors are happy, we get more sponsors, you get more Steam keys! It's a fair deal, right?
> > 
> > We don't sell Steam keys - we just give away them to our users. That's why we don't have money to give away hundreds of thousands of Steam keys like HumbleBundle or some other big stores. We have to find sponsors. And this is really hard nowadays. But we keep posting at least one giveaway every day.
> > 
> > We are OKAY about scripts helping you to complete tasks faster. But faking the completion of the tasks IS NOT OKAY.
> > 
> > You won't get a key from this giveaway, cheater. Sorry, but if you are going to continue cheating - you will be blocked on our service.
> > ```
> > 
> > 
> > **附加截图**
> > ![截屏2020-02-17下午4 20 30](https://user-images.githubusercontent.com/25281816/74635690-7a337a80-51a1-11ea-9cca-2674fa592962.png)
> 
> After completing the task, please close the script manager and ad blocking plugin.
> Then refresh the page and verify again.

Thank you! It works perfect,I love it,man:-)
