### ISSUE TITLE
Gleam.io - Function:$(document).keydown execution error, please see the console for details (red background part)!

### ISSUE THREAD

**Issue by azumukupoe** [HCLonely/auto-task-old#51]
- [x] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task/raw/master/auto-task.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task/raw/master/auto-task.user.js).
- [x] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [x] 我已经查看了[issues](https://github.com/HCLonely/auto-task/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task/issues) but not solved.

**关于哪一个网站，最好提供具体网址（必需）**[支持的网站](https://auto-task-doc.js.org/guide/#%E6%94%AF%E6%8C%81%E7%9A%84%E7%BD%91%E7%AB%99%E5%8F%8A%E4%BB%BB%E5%8A%A1)

gleam.io e.g. https://gleam.io/TzYX0/embed?l=https%3A%2F%2Fgame.intel.com%2Fww%2Fgiveaways%2Fbattlerite-all-champions-pack-key-giveaway

**使用的浏览器和脚本管理器**

FIrefox & Violentmonkey

**错误信息或截图(重要)**

![image](https://user-images.githubusercontent.com/31339007/140874012-87e2f42f-dcd5-4b93-ae25-37e6ae7654d0.png)

$(document).keydown
window.VMin0h1csi9e/</</</<@moz-extension://c3fe3915-e0c4-4427-9ad8-85e0f450d405/%20Auto%20Task.user.js#3:14133:29
dispatch@moz-extension://c3fe3915-e0c4-4427-9ad8-85e0f450d405/%20Auto%20Task.user.js#3:5:42571
add/v.handle@moz-extension://c3fe3915-e0c4-4427-9ad8-85e0f450d405/%20Auto%20Task.user.js#3:5:40572

**Comment by HCLonely** [comment]
Incompatible Violentmonkey
