### ISSUE TITLE
giveaway.su国内版：givee.club

### ISSUE THREAD

**Issue by inory121** [HCLonely/auto-task-old#52]
**关于哪一个网站**

https://givee.club/zh
![image](https://user-images.githubusercontent.com/35392664/141692134-8a3d9f4a-f8d7-4ce6-ac14-638c854e5b8e.png)

**关于哪一项功能**

auto-task

**期望的效果**

![image](https://user-images.githubusercontent.com/35392664/141692080-29bdc932-91db-4a0e-bb84-62e43f240683.png)

**Comment by HCLonely** [comment]
将在Ver 4.x版本中实装

**Comment by HCLonely** [comment]
已在 https://github.com/HCLonely/auto-task-v4 中实现
