### ISSUE TITLE
VK关注和和VK加群任务未完成

### ISSUE THREAD

**Issue by XmJwit** [HCLonely/auto-task-old#7]
**关于哪一个网站**

https://takekey.ru/distribution/36

**使用的浏览器和脚本管理器**
Chrome & Tampermonkey

**错误信息**

无，**VK关注和和VK加群任务未完成**

**附加截图**

![image](https://user-images.githubusercontent.com/36185379/75606470-0cd00400-5b28-11ea-84ac-ee97aa50cb3b.png)
![image](https://user-images.githubusercontent.com/36185379/75606482-3db03900-5b28-11ea-8c86-2c81a2cbb415.png)

**Comment by HCLonely** [comment]
vk任务需要手动完成，脚本不支持vk的任务
