### ISSUE TITLE
https://givekey.ru/

### ISSUE THREAD

**Issue by inory121** [HCLonely/auto-task-old#8]
**关于哪一个网站**

https://givekey.ru/

**使用的浏览器和脚本管理器**

Chrome  Tampermonkey

**错误信息**

Info:v-on handlerError:TypeError: Cannot set property 'message' of undefined    at Object.fuck (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=efcd8099-6815-4e79-b795-a56e717157c2:3689:44)    at click (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=efcd8099-6815-4e79-b795-a56e717157c2:6310:41)    at He (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=efcd8099-6815-4e79-b795-a56e717157c2:11:11384)    at a.n (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=efcd8099-6815-4e79-b795-a56e717157c2:11:13168)    at He (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=efcd8099-6815-4e79-b795-a56e717157c2:11:11384)    at a.e.$emit (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=efcd8099-6815-4e79-b795-a56e717157c2:11:34373)    at a.handleClick (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=efcd8099-6815-4e79-b795-a56e717157c2:12:124930)    at He (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=efcd8099-6815-4e79-b795-a56e717157c2:11:11384)    at HTMLButtonElement.n (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=efcd8099-6815-4e79-b795-a56e717157c2:11:13168)    at HTMLButtonElement.Yr.o._wrapper (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=efcd8099-6815-4e79-b795-a56e717157c2:11:48505)

**附加截图**

![QQ截图20200301122549](https://user-images.githubusercontent.com/35392664/75619551-739cfe00-5bb8-11ea-9a83-9776322d1238.png)

**Comment by HCLonely** [comment]
网页加载完成后等一会，打开控制台输入`Centrifuge`, 如果不报错就可以了，报错就再等等

**Comment by HCLonely** [comment]
也可以看一下谷歌人机验证有没有加载出来，一般人机验证加载出来就可以了

**Comment by inory121** [comment]
之前一直连接wss失败，刚才试了一下竟然可以了，见鬼了

**Comment by HCLonely** [comment]
> 之前一直连接wss失败，刚才试了一下竟然可以了，见鬼了

你点`init`的时候还有资源没加载就会出现这种情况，你多等一会再点就好了

**Comment by inory121** [comment]
谢谢大佬
